version: '3.0'

services:

  gobmessage:
    build: src
    container_name: gobmessage
    ports:
      - "8167:8000"
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "gobmessage.wsgi"
      UWSGI_CALLABLE: "app"
      UWSGI_PROCESSES: "4"
      UWSGI_ENABLE_THREADS: ""
      UWSGI_THREADS: ""
      API_HOST: http://gobapi:8001
      HR_KEYFILE: /app/${HR_KEYFILE}
      HR_CERTFILE: /app/${HR_CERTFILE}
      KVK_DATASERVICE_ADDRESS: ${KVK_DATASERVICE_ADDRESS}

networks:
  default:
    external:
      name: gob-network
