version: '3.0'

services:

  gobmessage:
    build: src
    container_name: gobmessage
    ports:
      - "8167:8000"
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "gobmessage.wsgi"
      UWSGI_CALLABLE: "app"
      UWSGI_PROCESSES: "4"
      UWSGI_ENABLE_THREADS: ""
      UWSGI_THREADS: ""
      API_HOST: http://gobapi:8001
      HR_KEYFILE: /app/${HR_KEYFILE}
      HR_CERTFILE: /app/${HR_CERTFILE}
      KVK_DATASERVICE_ADDRESS: ${KVK_DATASERVICE_ADDRESS}
      GOB_SHARED_DIR: /app/shared
      GOB_MESSAGE_DATABASE_HOST: message_database
      GOB_MESSAGE_DATABASE_PORT: 5432
    depends_on:
      - message_database
    volumes:
      - gob-volume:/app/shared

  message_database:
    image: amsterdam/postgres11
    ports:
      - "5411:5432"
    container_name: message_database
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: gob_message
      POSTGRES_USER: gob_message
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
    shm_size: '1gb'

volumes:
  gob-volume:
    external: true

networks:
  default:
    external:
      name: gob-network
