"""Initial migration. Create KvkUpdateMessage

Revision ID: 30024e1ebf53
Revises: 
Create Date: 2021-01-18 14:33:36.335896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30024e1ebf53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kvk_update_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kvk_nummer', sa.BigInteger(), nullable=True),
    sa.Column('vestigingsnummer', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kvk_update_message_id'), 'kvk_update_message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kvk_update_message_id'), table_name='kvk_update_message')
    op.drop_table('kvk_update_message')
    # ### end Alembic commands ###
