"""Remove vestigingsnummer from model

Revision ID: 94e2b2872f59
Revises: bb1c4a7514be
Create Date: 2021-03-11 10:56:08.728365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e2b2872f59'
down_revision = 'bb1c4a7514be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kvk_update_message', 'vestigingsnummer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kvk_update_message', sa.Column('vestigingsnummer', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
