"""Add received_at to KvkUpdateMssage. Add UpdateObject

Revision ID: bb1c4a7514be
Revises: 30024e1ebf53
Create Date: 2021-01-19 15:22:14.892400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1c4a7514be'
down_revision = '30024e1ebf53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('catalogue', sa.String(), nullable=True),
    sa.Column('collection', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_object_id'), 'update_object', ['id'], unique=False)
    op.add_column('kvk_update_message', sa.Column('received_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kvk_update_message', 'received_at')
    op.drop_index(op.f('ix_update_object_id'), table_name='update_object')
    op.drop_table('update_object')
    # ### end Alembic commands ###
