"""Add source and application to updateobject model

Revision ID: dd02075cbce6
Revises: e9da80c037eb
Create Date: 2021-03-18 09:26:28.558165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd02075cbce6'
down_revision = 'e9da80c037eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_object', sa.Column('application', sa.String(), nullable=True))
    op.add_column('update_object', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_object', 'source')
    op.drop_column('update_object', 'application')
    # ### end Alembic commands ###
