"""Add mapped_entity column to UpdateObject

Revision ID: e9da80c037eb
Revises: 94e2b2872f59
Create Date: 2021-03-18 06:17:31.258831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9da80c037eb'
down_revision = '94e2b2872f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_object', sa.Column('mapped_entity', sa.JSON(), nullable=True))
    op.add_column('update_object', sa.Column('update_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'update_object', 'kvk_update_message', ['update_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'update_object', type_='foreignkey')
    op.drop_column('update_object', 'update_message_id')
    op.drop_column('update_object', 'mapped_entity')
    # ### end Alembic commands ###
